export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR';
export const DISHES_COUNT = 'DISHES_COUNT';
export const ADD_DISH = 'ADD_DISH';
export const DELETE_DISH = 'DELETE_DISH';
export const TOTAL_PRICE = 'TOTAL_PRICE';